#
# version.cmake : version du projet
#

set (QQUALIF_MAJOR_VERSION "4")
set (QQUALIF_MINOR_VERSION "2")
set (QQUALIF_RELEASE_VERSION "0")
set (QQUALIF_VERSION ${QQUALIF_MAJOR_VERSION}.${QQUALIF_MINOR_VERSION}.${QQUALIF_RELEASE_VERSION})


