#
# version.cmake : version du projet
#

set (QQUALIF_MAJOR_VERSION "3")
set (QQUALIF_MINOR_VERSION "9")
set (QQUALIF_RELEASE_VERSION "1")
set (QQUALIF_VERSION ${QQUALIF_MAJOR_VERSION}.${QQUALIF_MINOR_VERSION}.${QQUALIF_RELEASE_VERSION})


